name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
permissions:
  pages: write 
  id-token: write

 
jobs:
  test:
    timeout-minutes: 60
    environment:
    name: github-pages
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test    
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/index.html
    - name: Setup Github Pages
      uses: actions/configure-pages@v5.0.0
    - name: Upload Artifact
      uses: actions/upload-pages-artifact@v3
      with:
       path: playwright-report/

    - name: Deploy Artifact to Github Pages
      id: deployment
      uses: actions/deploy-pages@v4

    - name: Deploy to the github-pages environment
      run: echo {page_url} = ${{ steps.deployment.outputs.page_url}}
    - name: Send mail
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.MAIL_USERNAME }}   # Optional (recommended) mail server username
        password: ${{ secrets.MAIL_PASSWORD }}   # Optional (recommended) mail server password
        subject: Github Actions job result       # Required mail subject
        to: ${{ secrets.MAIL_TO }}               # Required recipients' addresses
        from: ${{ secrets.MAIL_FROM }}           # Required sender full name (address can be skipped)
        body:  >
        Test results are available at: ${{ steps.deployment.outputs.page_url }} # Optional plain body
     

