name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
permissions:
  pages: write 
  id-token: write

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test    
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/index.html
    - name: Deploy adn publish playwright HTML report
      if: always() # We want this to always run, even if test fail prior to this step running
      id: deployment
      uses: peaceiris/actions-gh-pages@v4
      with:
          github_token: ${{ secrets.GH_PAT }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: playwright-report/
    - name: Get GitHub Pages URL
      run: echo "{page_url} = https://kaman-shaukat.github.io/Automation_Testing/">> $GITHUB_ENV
#      run: echo {page_url} = ${{ steps.deployment.outputs.page_url}}
    - name: Send mail
      uses: dawidd6/action-send-mail@v3
      with:
                server_address: smtp.gmail.com
                server_port: 465
                secure: true
                username: ${{ secrets.MAIL_USER_EMAIL }}
                password: ${{ secrets.MAIL_USER_PASSWORD }}
                subject: Playwright Test Results for Latest Build
                to: ${{ secrets.MAIL_TO }}
                from: ${{ secrets.MAIL_FROM }}
                body: Build job of ${{github.repository}} completed successfully!
                html_body: |
                  <html>
                    <body>
                        <p>Hi Team,</p>
                        <p>The latest build of <strong>${{ github.repository }}</strong> has completed its Playwright test execution.</p>
                        <p>All tests were executed automatically via the GitHub Actions pipeline. Please review the test report to address any failures.</p>
                        <p><a href="${{ env.page_url }}">Click here to view the detailed test report</a></p>
                    </body>
                  </html>
                ignore_cert: false
                convert_markdown: true
                priority: normal  

